//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationPrueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HologramaJedi
    {
        public int Id { get; set; }
        public int idHolograma { get; set; }
        public int idJedi { get; set; }
    
        public virtual Holograma Holograma { get; set; }
        public virtual Jedis Jedis { get; set; }
    }
}
