//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationPrueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jedis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jedis()
        {
            this.HologramaJedi = new HashSet<HologramaJedi>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int idGrado { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Direccion { get; set; }
        public string Color { get; set; }
    
        public virtual Grado Grado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HologramaJedi> HologramaJedi { get; set; }
    }
}
